--- #YAML:1.0
name: Posy-Plugin-MultiEntry
version: 0.01
author:
  - Kathryn Andersen
abstract: |-
  Posy plugin to enable multiple entries to display for special entry files.
license: perl
requires:
  Posy: 0.93
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::MultiEntry:
    file: lib/Posy/Plugin/MultiEntry.pm
    version: 0.01
generated_by: Module::Build version 0.2608
